
name: Build and publish to gh pages

on:
  push:
    branches: [ "*" ]
env:
  ASPNETCORE_ENVIRONMENT: Production
  WEBAPP_PATH: ./
  WEBAPP_CSPROJ: TestProject.csproj

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v4

      - name: Remove launchSettings.json (to not override ASPNETCORE_ENVIRONMENT)
        run: rm  ${{ env.WEBAPP_PATH }}Properties/launchSettings.json

      - name: Tailwind - download and run cli
        run: |
          wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss
          chmod +x /usr/local/bin/tailwindcss
          cd ${{ env.WEBAPP_PATH }}
          tailwindcss --input ./wwwroot/app.css  --output ./wwwroot/app.min.css  --minify
    
      - name: Change <base href="" /> in App.razor to match GitHub repo name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $NF}')
          if [[ "$REPO_NAME" != *.github.io ]]; then
            sed -i 's|<base href="/" />|<base href="/'$REPO_NAME'/" />|g' ${{ env.WEBAPP_PATH }}/Components/App.razor
          fi


      - run: touch ${{ env.WEBAPP_PATH }}/wwwroot/.nojekyll #folder starting with _ are handled as jekyll. This file will prevent that.  
      - name: Run webapp and generate static files
        run: |
          dotnet run --project ${{ env.WEBAPP_PATH }}${{env.WEBAPP_CSPROJ}}  --configuration Release

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.WEBAPP_PATH }}output
  
  
  
